customhost = "employee.czfxtgcswdmu.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "capc3009"
customdb = "employee"
custombucket = "yongchichun-bucket"
customregion = "us-east-1"